runSimulator: CacheEntry.o CacheSet.o Cache.o main.o

CacheEntry.o: CacheEntry.cc CacheEntry.h
	cc -c CacheEntry.cc

CacheSet.o: CacheSet.cc CacheEntry.h
	cc -c CacheSet.cc

Cache.o: Cache.cc Cache.h
	cc -c Cache.cc

main.o: main.cc
	cc -c main.cc
